### ISSUE TITLE
Resolve uses flagSet default as the final value to choose, but is documented otherwise

### ISSUE THREAD

**Issue by stephensearles** [mreiferson/go-options#13]
Resolve uses flagSet default as the final value to choose, but it is documented to use the given option struct's value struct as the final value. Chasing https://github.com/nsqio/nsq/issues/826 revealed that the missing broadcast-address was the culprit for the weird message timing I saw, and the reason it wasn't pulled is because the implementation isn't doing what callers expect.

That said, I'm not sure how this package is used beyond just nsq and if it's actually the documentation that should change in this case.

**Comment by mreiferson** [comment]
see #14
