### ISSUE TITLE
Custom flags support

### ISSUE THREAD

**Issue by jaytaylor** [mreiferson/go-options#7]
See https://github.com/mreiferson/go-options/pull/4 for the start of the conversation.

----

@RobCherry Ok, so I'm not sure what the right behavior would be for the flag.Value case, but I do have it recognizing some specific aliased predefined custom types.

The limitations here are pretty severe, as only basic aliased types with a recognized and supported underlying structure (i.e. `[]string`, `[]float64`, `[]int`, and `[]int64`) are implemented.

See: https://github.com/jaytaylor/go-options/blob/jay/flag-interfaces-compatibility/flag_interfaces_test.go

Given the other limitations of this library (no ability to traverse nested objects), I am inclined to leave it as is unless we're able to invest the time to think through it fully and get it right.

@mreiferson thoughts?

**Comment by mreiferson** [comment]
I think the only change _required_ (right now) is to not assume that we can type assert to `flag.Getter`

We can separately talk about custom options.

**Comment by jaytaylor** [comment]
BTW, have you guys seen [Viper](https://github.com/spf13/viper)?  It looks like it may do a lot of what flag+toml+options provides, and more.

**Comment by jaytaylor** [comment]
Closing this because I'm happy with the current behavior and capabilities of the go-options package.
